service: media-s3-sync

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        Fn::Join:
           - ""
           - - "arn:aws:s3:::env:${env:AWS_S3_BUCKET}"
functions:
  create:
    handler: src/handler.create
    timeout: 30
    events:
      - existingS3:
          bucket: ${env:AWS_S3_BUCKET}
          events:
            - s3:ObjectCreated:*
    environment:
      AWS_S3_ACCESS_KEY_ID: ${env:AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${env:AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
      AWS_S3_REGION: ${env:AWS_S3_REGION}
      AWS_S3_VERSION: ${env:AWS_S3_VERSION}
      AWS_ELASTIC_SEARCH_HOST: ${env:AWS_ELASTIC_SEARCH_HOST}
      AWS_ELASTIC_SEARCH_PREFIX: ${env:AWS_ELASTIC_SEARCH_PREFIX}

  remove:
    handler: src/handler.remove
    timeout: 30
    events:
      - existingS3:
          bucket: ${env:AWS_S3_BUCKET}
          events:
            - s3:ObjectRemoved:*
    environment:
      AWS_S3_ACCESS_KEY_ID: ${env:AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${env:AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
      AWS_S3_REGION: ${env:AWS_S3_REGION}
      AWS_S3_VERSION: ${env:AWS_S3_VERSION}
      AWS_ELASTIC_SEARCH_HOST: ${env:AWS_ELASTIC_SEARCH_HOST}
      AWS_ELASTIC_SEARCH_PREFIX: ${env:AWS_ELASTIC_SEARCH_PREFIX}

  migrate:
    handler: src/handler.migrate
    timeout: 300
    events:
      - http:
          path: /migration
          method: post
    environment:
      AWS_S3_ACCESS_KEY_ID: ${env:AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${env:AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
      AWS_S3_REGION: ${env:AWS_S3_REGION}
      AWS_S3_VERSION: ${env:AWS_S3_VERSION}
      AWS_ELASTIC_SEARCH_HOST: ${env:AWS_ELASTIC_SEARCH_HOST}
      AWS_ELASTIC_SEARCH_PREFIX: ${env:AWS_ELASTIC_SEARCH_PREFIX}

  clean:
    handler: src/handler.clean
    timeout: 300
    events:
      - http:
          path: /clean
          method: post
    environment:
      AWS_S3_ACCESS_KEY_ID: ${env:AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${env:AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
      AWS_S3_REGION: ${env:AWS_S3_REGION}
      AWS_S3_VERSION: ${env:AWS_S3_VERSION}
      AWS_ELASTIC_SEARCH_HOST: ${env:AWS_ELASTIC_SEARCH_HOST}
      AWS_ELASTIC_SEARCH_PREFIX: ${env:AWS_ELASTIC_SEARCH_PREFIX}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-existing-s3

custom:
  serverless-offline:
    port: 3010
    host: 0.0.0.0

  webpack:
    webpackConfig: internals/webpack.config.js
